export const TITLE = "Follow The Grant"
export const DESCRIPTION = "Data and investigations about potential conflicts of interest within academic research"
export const CATALOG_URL = "https://s3.investigativedata.org/data.followthegrant.org/catalog.json"
export const STORIES_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQ5TDRD2bmymvHdND82pHLDT-ki4QGEGrqJ6Hmnl2pFkkEz2b1ww5GTXi15YgyXuS6773zaQjQ7t1su/pub?gid=0&single=true&output=csv"
export const AWARDS_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQSj7Ohzzaz334H7BTFRPGTxxphX5I3TcLerb3MKIMBTyUmG-vHv_YBJkOYDtjtN-3ByP8pDlmt1Rv2/pub?gid=0&single=true&output=csv"
